name: Test Token

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test token
        run: |
          echo "Token exists: ${{ secrets.SNAKENV: }}
          echo "Token length: ${{ secrets.SNAKENS: }}"
        env:
          TOKEN: ${{ secrets.SNAKE_TOKEN }}
